# Dockerfile.prefect
FROM prefecthq/prefect:3.4-python3.12-conda

WORKDIR /opt/prefect

RUN apt-get update && apt-get install -y --no-install-recommends \
    openjdk-17-jdk \
    curl \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

ENV JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64
ENV PATH="${JAVA_HOME}/bin:${PATH}"
ENV PYTHONUNBUFFERED=1

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# COPY ./src /opt/prefect/src

# Startup script
COPY src/utils/prefect_startup.sh ./startup.sh
RUN chmod +x ./startup.sh

# Add alias-like script for running flows
RUN echo -e '#!/bin/bash\npython /opt/prefect/src/flows.py "$@"' > /usr/local/bin/runflows \
    && chmod +x /usr/local/bin/runflows

CMD ["bash", "./startup.sh"]